# Generated by Django 5.0.1 on 2024-01-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_newsletter_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
